In [2]:
# Import necessary libraries
import pandas as pd
import os
import platform
device_name = platform.node()

previous_folder = os.getcwd()
print ("This is the working folder: " + previous_folder)

if device_name == 'mmd-MS-7D98': 
    #This passage is done because everytime I log into the remote server the default folder is:
    #/mmd/home and I need to localize the correct folder to load the settings 
    os.chdir("/media/mmd/Samsung_T5/GitHub/UMD")

if previous_folder != os.getcwd(): # This is now the right working folder
    print("The current working folder has been changed, now the working folder is: " + os.getcwd())

This is the working folder: /media/mmd/Samsung_T5/GitHub/UMD/visualization
The current working folder has been changed, now the working folder is: /media/mmd/Samsung_T5/GitHub/UMD


In [3]:
import sys
sys.path.append("..")
sys.path.append("my_library")
from my_library.config import *
from my_library.metrics.cmp_metrics import *
sys.path.append("..")
import os

n_classes = 2

import os

#%run -i visualization/compute_metrics_single_run.ipynb


/home/mmd/anaconda3/envs/sf3/lib/python3.9/site-packages/timm/models/helpers.py:7: FutureWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
/home/mmd/anaconda3/envs/sf3/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)


this is the current directory:  /media/mmd/Samsung_T5/GitHub/UMD
This is the thesis folder, where all the code is located:  GitHub/UMD
Questo è samsung:/media/mmd/Samsung_T5


In [4]:
base_folder = os.path.join(working_directory,"eval/train")
subfolder = [name for name in os.listdir(base_folder) if os.path.isdir(os.path.join(base_folder, name))]

print(subfolder)

train_metrics = {}
train_class_metrics = {}
outer_train_metrics = {}
outer_train_class_metrics = {}

for m in subfolder:
    parent_directory = os.path.join(base_folder, m)
    subsubfolder = [name for name in os.listdir(parent_directory) if os.path.isdir(os.path.join(parent_directory, name))]
    print(subsubfolder)
    train_metrics = {}
    train_class_metrics = {}
    for s in subsubfolder: 
        sub_parent_directory = os.path.join(parent_directory, s)
        print(sub_parent_directory)
        print(s)
        train_metrics[s], train_class_metrics[s], a, n = compute_metrics(sub_parent_directory, n_classes, sub_parent_directory)
    outer_train_metrics[m] = train_metrics
    outer_train_class_metrics[m] =train_class_metrics


['adsq', 'br3', 'pdl1-3']
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/adsq/inner_iteration_1
inner_iteration_1


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.8975409836065574,
 'Balanced_Accuracy': 0.9352331606217616,
 'Precision': 0.9312446074201898,
 'Recall': 0.8975409836065574,
 'F1-Score': 0.9040777825890605,
 'Confusion Matrix': [[168, 25], [0, 51]]}

Accuracy: 0.8975409836065574
Balanced_Accuracy: 0.9352331606217616
Precision: 0.9312446074201898
Recall: 0.8975409836065574
F1-Score: 0.9040777825890605
Confusion Matrix: [[168, 25], [0, 51]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/adsq/inner_iteration_2
inner_iteration_2


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.8433734939759037,
 'Balanced_Accuracy': 0.9029850746268657,
 'Precision': 0.9135853759867054,
 'Recall': 0.8433734939759037,
 'F1-Score': 0.8575835020522863,
 'Confusion Matrix': [[162, 39], [0, 48]]}

Accuracy: 0.8433734939759037
Balanced_Accuracy: 0.9029850746268657
Precision: 0.9135853759867054
Recall: 0.8433734939759037
F1-Score: 0.8575835020522863
Confusion Matrix: [[162, 39], [0, 48]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/adsq/inner_iteration_3
inner_iteration_3


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.9166666666666666,
 'Balanced_Accuracy': 0.9477611940298507,
 'Precision': 0.9409722222222222,
 'Recall': 0.9166666666666666,
 'F1-Score': 0.9214838998783688,
 'Confusion Matrix': [[180, 21], [0, 51]]}

Accuracy: 0.9166666666666666
Balanced_Accuracy: 0.9477611940298507
Precision: 0.9409722222222222
Recall: 0.9166666666666666
F1-Score: 0.9214838998783688
Confusion Matrix: [[180, 21], [0, 51]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/adsq/inner_iteration_4
inner_iteration_4


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.8656126482213439,
 'Balanced_Accuracy': 0.916256157635468,
 'Precision': 0.9200075287031809,
 'Recall': 0.8656126482213439,
 'F1-Score': 0.8765204323911489,
 'Confusion Matrix': [[169, 34], [0, 50]]}

Accuracy: 0.8656126482213439
Balanced_Accuracy: 0.916256157635468
Precision: 0.9200075287031809
Recall: 0.8656126482213439
F1-Score: 0.8765204323911489
Confusion Matrix: [[169, 34], [0, 50]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/adsq/inner_iteration_5
inner_iteration_5


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.9015748031496063,
 'Balanced_Accuracy': 0.9381188118811881,
 'Precision': 0.9335310358932406,
 'Recall': 0.9015748031496063,
 'F1-Score': 0.9078659148093693,
 'Confusion Matrix': [[177, 25], [0, 52]]}

Accuracy: 0.9015748031496063
Balanced_Accuracy: 0.9381188118811881
Precision: 0.9335310358932406
Recall: 0.9015748031496063
F1-Score: 0.9078659148093693
Confusion Matrix: [[177, 25], [0, 52]]
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/br3/inner_iteration_1
inner_iteration_1


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3481781376518219,
 'Balanced_Accuracy': 0.3536237947246792,
 'Precision': 0.3549452041630631,
 'Recall': 0.3481781376518219,
 'F1-Score': 0.336152697846558,
 'Confusion Matrix': [[18, 33, 43], [13, 24, 27], [17, 28, 44]]}

Accuracy: 0.3481781376518219
Balanced_Accuracy: 0.3536237947246792
Precision: 0.3549452041630631
Recall: 0.3481781376518219
F1-Score: 0.336152697846558
Confusion Matrix: [[18, 33, 43], [13, 24, 27], [17, 28, 44]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/br3/inner_iteration_2
inner_iteration_2


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3665338645418327,
 'Balanced_Accuracy': 0.3473036398467433,
 'Precision': 0.3832870273292794,
 'Recall': 0.3665338645418327,
 'F1-Score': 0.3279582746721565,
 'Confusion Matrix': [[27, 8, 65], [11, 6, 47], [26, 2, 59]]}

Accuracy: 0.3665338645418327
Balanced_Accuracy: 0.3473036398467433
Precision: 0.3832870273292794
Recall: 0.3665338645418327
F1-Score: 0.3279582746721565
Confusion Matrix: [[27, 8, 65], [11, 6, 47], [26, 2, 59]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/br3/inner_iteration_3
inner_iteration_3


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.572,
 'Balanced_Accuracy': 0.5730837789661319,
 'Precision': 0.5825654116948236,
 'Recall': 0.572,
 'F1-Score': 0.5736812305721478,
 'Confusion Matrix': [[61, 21, 20], [12, 41, 13], [18, 23, 41]]}

Accuracy: 0.572
Balanced_Accuracy: 0.5730837789661319
Precision: 0.5825654116948236
Recall: 0.572
F1-Score: 0.5736812305721478
Confusion Matrix: [[61, 21, 20], [12, 41, 13], [18, 23, 41]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/br3/inner_iteration_4
inner_iteration_4


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3442622950819672,
 'Balanced_Accuracy': 0.32232919354321105,
 'Precision': 0.33184181655281797,
 'Recall': 0.3442622950819672,
 'F1-Score': 0.3275545687723674,
 'Confusion Matrix': [[51, 17, 26], [42, 10, 13], [44, 18, 23]]}

Accuracy: 0.3442622950819672
Balanced_Accuracy: 0.32232919354321105
Precision: 0.33184181655281797
Recall: 0.3442622950819672
F1-Score: 0.3275545687723674
Confusion Matrix: [[51, 17, 26], [42, 10, 13], [44, 18, 23]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/br3/inner_iteration_5
inner_iteration_5


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.5912698412698413,
 'Balanced_Accuracy': 0.6099918273273008,
 'Precision': 0.6423466117216118,
 'Recall': 0.5912698412698413,
 'F1-Score': 0.5948862702306172,
 'Confusion Matrix': [[46, 38, 14], [9, 49, 7], [10, 25, 54]]}

Accuracy: 0.5912698412698413
Balanced_Accuracy: 0.6099918273273008
Precision: 0.6423466117216118
Recall: 0.5912698412698413
F1-Score: 0.5948862702306172
Confusion Matrix: [[46, 38, 14], [9, 49, 7], [10, 25, 54]]
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/pdl1-3/inner_iteration_1
inner_iteration_1


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.5504587155963303,
 'Balanced_Accuracy': 0.5548245614035088,
 'Precision': 0.5619339841118859,
 'Recall': 0.5504587155963303,
 'F1-Score': 0.5512886754904546,
 'Confusion Matrix': [[39, 12, 27], [18, 41, 17], [12, 12, 40]]}

Accuracy: 0.5504587155963303
Balanced_Accuracy: 0.5548245614035088
Precision: 0.5619339841118859
Recall: 0.5504587155963303
F1-Score: 0.5512886754904546
Confusion Matrix: [[39, 12, 27], [18, 41, 17], [12, 12, 40]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/pdl1-3/inner_iteration_2
inner_iteration_2


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.7300884955752213,
 'Balanced_Accuracy': 0.7348093673394879,
 'Precision': 0.7440370659735265,
 'Recall': 0.7300884955752213,
 'F1-Score': 0.7292307604143833,
 'Confusion Matrix': [[52, 16, 15], [5, 62, 10], [5, 10, 51]]}

Accuracy: 0.7300884955752213
Balanced_Accuracy: 0.7348093673394879
Precision: 0.7440370659735265
Recall: 0.7300884955752213
F1-Score: 0.7292307604143833
Confusion Matrix: [[52, 16, 15], [5, 62, 10], [5, 10, 51]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/pdl1-3/inner_iteration_3
inner_iteration_3


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.5605381165919282,
 'Balanced_Accuracy': 0.5748742723993054,
 'Precision': 0.6224672915313122,
 'Recall': 0.5605381165919282,
 'F1-Score': 0.5512112050144851,
 'Confusion Matrix': [[33, 9, 35], [12, 34, 33], [5, 4, 58]]}

Accuracy: 0.5605381165919282
Balanced_Accuracy: 0.5748742723993054
Precision: 0.6224672915313122
Recall: 0.5605381165919282
F1-Score: 0.5512112050144851
Confusion Matrix: [[33, 9, 35], [12, 34, 33], [5, 4, 58]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/pdl1-3/inner_iteration_4
inner_iteration_4


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.8628318584070797,
 'Balanced_Accuracy': 0.8676044634377967,
 'Precision': 0.8739346655973242,
 'Recall': 0.8628318584070797,
 'F1-Score': 0.8638723377591706,
 'Confusion Matrix': [[65, 5, 10], [3, 69, 9], [1, 3, 61]]}

Accuracy: 0.8628318584070797
Balanced_Accuracy: 0.8676044634377967
Precision: 0.8739346655973242
Recall: 0.8628318584070797
F1-Score: 0.8638723377591706
Confusion Matrix: [[65, 5, 10], [3, 69, 9], [1, 3, 61]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/train/pdl1-3/inner_iteration_5
inner_iteration_5


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.7397260273972602,
 'Balanced_Accuracy': 0.7532430819486761,
 'Precision': 0.7940137802159999,
 'Recall': 0.7397260273972602,
 'F1-Score': 0.743544288469898,
 'Confusion Matrix': [[48, 2, 28], [8, 56, 15], [2, 2, 58]]}

Accuracy: 0.7397260273972602
Balanced_Accuracy: 0.7532430819486761
Precision: 0.7940137802159999
Recall: 0.7397260273972602
F1-Score: 0.743544288469898
Confusion Matrix: [[48, 2, 28], [8, 56, 15], [2, 2, 58]]


In [5]:
outer_train_metrics["pdl1-3"]["inner_iteration_1"]

{'Accuracy': 0.5504587155963303,
 'Balanced_Accuracy': 0.5548245614035088,
 'Precision': 0.5619339841118859,
 'Recall': 0.5504587155963303,
 'F1-Score': 0.5512886754904546,
 'Confusion Matrix': [[39, 12, 27], [18, 41, 17], [12, 12, 40]]}

In [6]:
import numpy as np
import pandas as pd
from scipy.stats import sem

#train_metrics
for key, value in outer_train_metrics.items():
    print(f"Chiave: {key}, Valore: {value}")
    train_metrics = value
    # Extract metrics
    metrics = list(train_metrics['inner_iteration_1'].keys())
    #metrics = metrics[:-1]
    print(metrics)

    # Compute mean and confidence interval for each metric
    summary = {}
    n = len(train_metrics)  # Number of iterations

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        print(values)
        mean_value = np.mean(values)
        confidence_interval = 2 * np.std(values, ddof=1) / np.sqrt(n)  # 2 * standard error of the mean
        
        summary[metric] = {'Mean': mean_value, 'Confidence Interval': confidence_interval}

    # Convert results to a DataFrame for visualization
    summary_df = pd.DataFrame(summary).T

    display(summary_df)

    metrics = ['Confusion Matrix']

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        #print(values)


    # Compute the mean confusion matrix
    mean_confusion_matrix = np.mean(values, axis=0)
    print(mean_confusion_matrix)

    # Compute the confidence interval (2 * standard error of the mean)
    n_matrices = values.shape[0]
    confidence_interval_matrix = 2 * np.std(values, axis=0, ddof=1) / np.sqrt(n_matrices)

    # Convert to DataFrame for better visualization
    size = mean_confusion_matrix.shape[0]
    
    mean_confusion_df = pd.DataFrame(mean_confusion_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    confidence_interval_df = pd.DataFrame(confidence_interval_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    

    display(mean_confusion_df)
    display(confidence_interval_df)

Chiave: adsq, Valore: {'inner_iteration_1': {'Accuracy': 0.8975409836065574, 'Balanced_Accuracy': 0.9352331606217616, 'Precision': 0.9312446074201898, 'Recall': 0.8975409836065574, 'F1-Score': 0.9040777825890605, 'Confusion Matrix': [[168, 25], [0, 51]]}, 'inner_iteration_2': {'Accuracy': 0.8433734939759037, 'Balanced_Accuracy': 0.9029850746268657, 'Precision': 0.9135853759867054, 'Recall': 0.8433734939759037, 'F1-Score': 0.8575835020522863, 'Confusion Matrix': [[162, 39], [0, 48]]}, 'inner_iteration_3': {'Accuracy': 0.9166666666666666, 'Balanced_Accuracy': 0.9477611940298507, 'Precision': 0.9409722222222222, 'Recall': 0.9166666666666666, 'F1-Score': 0.9214838998783688, 'Confusion Matrix': [[180, 21], [0, 51]]}, 'inner_iteration_4': {'Accuracy': 0.8656126482213439, 'Balanced_Accuracy': 0.916256157635468, 'Precision': 0.9200075287031809, 'Recall': 0.8656126482213439, 'F1-Score': 0.8765204323911489, 'Confusion Matrix': [[169, 34], [0, 50]]}, 'inner_iteration_5': {'Accuracy': 0.9015748031

Mean  Confidence Interval
Accuracy            0.884954             0.026621
Balanced_Accuracy   0.928071             0.016179
Precision           0.927868             0.009808
Recall              0.884954             0.026621
F1-Score            0.893506             0.023150
Confusion Matrix   62.600000            59.986244

[[171.2  28.8]
 [  0.   50.4]]


Pred_0  Pred_1
True_0   171.2    28.8
True_1     0.0    50.4

Pred_0    Pred_1
True_0  6.493073  6.645299
True_1  0.000000  1.356466

Chiave: br3, Valore: {'inner_iteration_1': {'Accuracy': 0.3481781376518219, 'Balanced_Accuracy': 0.3536237947246792, 'Precision': 0.3549452041630631, 'Recall': 0.3481781376518219, 'F1-Score': 0.336152697846558, 'Confusion Matrix': [[18, 33, 43], [13, 24, 27], [17, 28, 44]]}, 'inner_iteration_2': {'Accuracy': 0.3665338645418327, 'Balanced_Accuracy': 0.3473036398467433, 'Precision': 0.3832870273292794, 'Recall': 0.3665338645418327, 'F1-Score': 0.3279582746721565, 'Confusion Matrix': [[27, 8, 65], [11, 6, 47], [26, 2, 59]]}, 'inner_iteration_3': {'Accuracy': 0.572, 'Balanced_Accuracy': 0.5730837789661319, 'Precision': 0.5825654116948236, 'Recall': 0.572, 'F1-Score': 0.5736812305721478, 'Confusion Matrix': [[61, 21, 20], [12, 41, 13], [18, 23, 41]]}, 'inner_iteration_4': {'Accuracy': 0.3442622950819672, 'Balanced_Accuracy': 0.32232919354321105, 'Precision': 0.33184181655281797, 'Recall': 0.3442622950819672, 'F1-Score': 0.3275545687723674, 'Confusion Matrix': [[51, 17, 26], [42, 10, 13], [4

Mean  Confidence Interval
Accuracy            0.444449             0.112429
Balanced_Accuracy   0.441266             0.123693
Precision           0.458997             0.127760
Recall              0.444449             0.112429
F1-Score            0.432047             0.124520
Confusion Matrix   27.644444            14.958312

[[40.6 23.4 33.6]
 [17.4 26.  21.4]
 [23.  19.2 44.2]]


Pred_0  Pred_1  Pred_2
True_0    40.6    23.4    33.6
True_1    17.4    26.0    21.4
True_2    23.0    19.2    44.2

Pred_0     Pred_1     Pred_2
True_0  15.806328  10.855413  18.445596
True_1  12.370934  16.816658  14.388885
True_2  11.661904   9.195651  12.448293

Chiave: pdl1-3, Valore: {'inner_iteration_1': {'Accuracy': 0.5504587155963303, 'Balanced_Accuracy': 0.5548245614035088, 'Precision': 0.5619339841118859, 'Recall': 0.5504587155963303, 'F1-Score': 0.5512886754904546, 'Confusion Matrix': [[39, 12, 27], [18, 41, 17], [12, 12, 40]]}, 'inner_iteration_2': {'Accuracy': 0.7300884955752213, 'Balanced_Accuracy': 0.7348093673394879, 'Precision': 0.7440370659735265, 'Recall': 0.7300884955752213, 'F1-Score': 0.7292307604143833, 'Confusion Matrix': [[52, 16, 15], [5, 62, 10], [5, 10, 51]]}, 'inner_iteration_3': {'Accuracy': 0.5605381165919282, 'Balanced_Accuracy': 0.5748742723993054, 'Precision': 0.6224672915313122, 'Recall': 0.5605381165919282, 'F1-Score': 0.5512112050144851, 'Confusion Matrix': [[33, 9, 35], [12, 34, 33], [5, 4, 58]]}, 'inner_iteration_4': {'Accuracy': 0.8628318584070797, 'Balanced_Accuracy': 0.8676044634377967, 'Precision': 0.8739346655973242, 'Recall': 0.8628318584070797, 'F1-Score': 0.8638723377591706, 'Confusion Matrix': [[65,

Mean  Confidence Interval
Accuracy            0.688729             0.118469
Balanced_Accuracy   0.697071             0.117326
Precision           0.719277             0.113355
Recall              0.688729             0.118469
F1-Score            0.687829             0.120927
Confusion Matrix   24.711111            19.063170

[[47.4  8.8 23. ]
 [ 9.2 52.4 16.8]
 [ 5.   6.2 53.6]]


Pred_0  Pred_1  Pred_2
True_0    47.4     8.8    23.0
True_1     9.2    52.4    16.8
True_2     5.0     6.2    53.6

Pred_0     Pred_1    Pred_2
True_0  11.038116   4.955805  9.143304
True_1   5.344156  13.032268  8.634813
True_2   3.847077   4.019950  7.552483

In [7]:
outer_train_metrics

{'adsq': {'inner_iteration_1': {'Accuracy': 0.8975409836065574,
   'Balanced_Accuracy': 0.9352331606217616,
   'Precision': 0.9312446074201898,
   'Recall': 0.8975409836065574,
   'F1-Score': 0.9040777825890605,
   'Confusion Matrix': [[168, 25], [0, 51]]},
  'inner_iteration_2': {'Accuracy': 0.8433734939759037,
   'Balanced_Accuracy': 0.9029850746268657,
   'Precision': 0.9135853759867054,
   'Recall': 0.8433734939759037,
   'F1-Score': 0.8575835020522863,
   'Confusion Matrix': [[162, 39], [0, 48]]},
  'inner_iteration_3': {'Accuracy': 0.9166666666666666,
   'Balanced_Accuracy': 0.9477611940298507,
   'Precision': 0.9409722222222222,
   'Recall': 0.9166666666666666,
   'F1-Score': 0.9214838998783688,
   'Confusion Matrix': [[180, 21], [0, 51]]},
  'inner_iteration_4': {'Accuracy': 0.8656126482213439,
   'Balanced_Accuracy': 0.916256157635468,
   'Precision': 0.9200075287031809,
   'Recall': 0.8656126482213439,
   'F1-Score': 0.8765204323911489,
   'Confusion Matrix': [[169, 34], [0, 

In [8]:
outer_train_class_metrics["adsq"]

{'inner_iteration_1': {'Class_0': {'Accuracy': 0.8704663212435233,
   'Precision': 1.0,
   'Recall': 0.8704663212435233,
   'F1-score': 0.9307479224376731},
  'Class_1': {'Accuracy': 1.0,
   'Precision': 0.6710526315789473,
   'Recall': 1.0,
   'F1-score': 0.8031496062992126}},
 'inner_iteration_2': {'Class_0': {'Accuracy': 0.8059701492537313,
   'Precision': 1.0,
   'Recall': 0.8059701492537313,
   'F1-score': 0.8925619834710744},
  'Class_1': {'Accuracy': 1.0,
   'Precision': 0.5517241379310345,
   'Recall': 1.0,
   'F1-score': 0.7111111111111111}},
 'inner_iteration_3': {'Class_0': {'Accuracy': 0.8955223880597015,
   'Precision': 1.0,
   'Recall': 0.8955223880597015,
   'F1-score': 0.9448818897637795},
  'Class_1': {'Accuracy': 1.0,
   'Precision': 0.7083333333333334,
   'Recall': 1.0,
   'F1-score': 0.8292682926829268}},
 'inner_iteration_4': {'Class_0': {'Accuracy': 0.8325123152709359,
   'Precision': 1.0,
   'Recall': 0.8325123152709359,
   'F1-score': 0.9086021505376344},
  'Cla

In [9]:
# ------------------------------------------------------------------------------
# Function to compute a simple 95% confidence interval ≈ mean ± 2 * (std / sqrt(n))
# ------------------------------------------------------------------------------
def compute_mean_and_ci(values):
    """
    Returns (mean, ci) where ci is an approximate +/- 95% confidence interval
    using 2 * standard_error. (You could also switch to a t- or z-based formula.)
    """
    arr = np.array(values, dtype=float)
    mean_val = arr.mean()
    n = len(arr)
    if n > 1:
        std_err = arr.std(ddof=1) / np.sqrt(n)
        ci = 2.0 * std_err  # Approx 95% if n is reasonably large
    else:
        # If only one sample, CI is 0
        ci = 0.0
    return mean_val, ci

In [10]:
from pyexpat import model
import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# Collect and summarize
# ------------------------------------------------------------------------------
results_list = []  # We'll accumulate dictionaries to later convert to a DataFrame

# outer_train_class_metrics might have multiple top-level keys (e.g., 'br3', 'br4', etc.)
for model_key, inner_dict in outer_train_class_metrics.items():
    # inner_dict looks like:
    # {
    #   'inner_iteration_5': {'Class_0': {...}, 'Class_1': {...}, ...},
    #   'inner_iteration_4': {...},
    #   'inner_iteration_3': {...}
    # }
    print(model_key)
    # 1) Identify all available "inner_iteration" keys
    iteration_keys = list(inner_dict.keys())
    print(iteration_keys)

    # 2) From the first iteration, identify the classes
    #    (Assumes same classes appear in each iteration, or you can unify them if needed)
    first_iteration = iteration_keys[0]
    class_names = list(inner_dict[first_iteration].keys())
    print(class_names)
    
    # 3) For each class, gather metric lists across iterations
    for class_name in class_names:
        # We'll track each metric: Accuracy, Precision, Recall, F1-score
        # You could also extract these keys on the fly if each class dict has more/less.
        metric_names = ["Accuracy", "Precision", "Recall", "F1-score"]
        
        # For storing raw values across all iterations
        metrics_storage = {metric: [] for metric in metric_names}
        
        # 4) Loop over each iteration to collect values
        for iteration_key in iteration_keys:
            iteration_data = inner_dict[iteration_key]
            if class_name in iteration_data:
                class_metrics = iteration_data[class_name]
                # class_metrics is e.g. {'Accuracy': 0.81, 'Precision': 0.82, ...}
                for metric in metric_names:
                    if metric in class_metrics:
                        metrics_storage[metric].append(class_metrics[metric])
        
        # 5) Compute mean & CI for each metric in metrics_storage
        for metric, values in metrics_storage.items():
            if len(values) == 0:
                continue  # skip if no data was found for some reason
            
            mean_val, ci_val = compute_mean_and_ci(values)

            results_list.append({
                "Model":  model_key,
                "Class":  class_name,
                "Metric": metric,
                "Mean":   mean_val,
                "95% CI": ci_val
            })

# ------------------------------------------------------------------------------
# Convert the collected results into a DataFrame
# ------------------------------------------------------------------------------
summary_df = pd.DataFrame(results_list)

# If desired, you can pivot or group:
# e.g., pivot to see each (Class, Metric) as a row with columns = ["Mean", "95% CI"]
# We'll keep it in "long" format here:
display(summary_df)

#Optionally, you could pivot for a more "matrix-like" view:
pivot_df = summary_df.pivot(index=["Model","Class"], 
                             columns="Metric", 
                            values=["Mean","95% CI"])
display(pivot_df)


adsq
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1']
br3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']
pdl1-3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']


Model    Class     Metric      Mean    95% CI
0     adsq  Class_0   Accuracy  0.856142  0.032359
1     adsq  Class_0  Precision  1.000000  0.000000
2     adsq  Class_0     Recall  0.856142  0.032359
3     adsq  Class_0   F1-score  0.922166  0.018926
4     adsq  Class_1   Accuracy  1.000000  0.000000
5     adsq  Class_1  Precision  0.640335  0.057753
6     adsq  Class_1     Recall  1.000000  0.000000
7     adsq  Class_1   F1-score  0.779200  0.043658
8      br3  Class_0   Accuracy  0.414294  0.157296
9      br3  Class_0  Precision  0.509432  0.148155
10     br3  Class_0     Recall  0.414294  0.157296
11     br3  Class_0   F1-score  0.444178  0.140956
12     br3  Class_1   Accuracy  0.399531  0.256572
13     br3  Class_1  Precision  0.359886  0.096139
14     br3  Class_1     Recall  0.399531  0.256572
15     br3  Class_1   F1-score  0.350137  0.171936
16     br3  Class_2   Accuracy  0.509975  0.138057
17     br3  Class_2  Precision  0.475203  0.142770
18     br3  Class_2     Recall  0.509975  0.138057
19     br3  Class_2   F1-score  0.477593  0.113594
20  pdl1-3  Class_0   Accuracy  0.596592  0.130710
21  pdl1-3  Class_0  Precision  0.766708  0.135361
22  pdl1-3  Class_0     Recall  0.596592  0.130710
23  pdl1-3  Class_0   F1-score  0.669181  0.131559
24  pdl1-3  Class_1   Accuracy  0.667152  0.159545
25  pdl1-3  Class_1  Precision  0.777631  0.116730
26  pdl1-3  Class_1     Recall  0.667152  0.159545
27  pdl1-3  Class_1   F1-score  0.710386  0.128920
28  pdl1-3  Class_2   Accuracy  0.827469  0.117844
29  pdl1-3  Class_2  Precision  0.588864  0.115184
30  pdl1-3  Class_2     Recall  0.827469  0.117844
31  pdl1-3  Class_2   F1-score  0.682584  0.104081

Mean                                  95% CI            \
Metric          Accuracy  F1-score Precision    Recall  Accuracy  F1-score   
Model  Class                                                                 
adsq   Class_0  0.856142  0.922166  1.000000  0.856142  0.032359  0.018926   
       Class_1  1.000000  0.779200  0.640335  1.000000  0.000000  0.043658   
br3    Class_0  0.414294  0.444178  0.509432  0.414294  0.157296  0.140956   
       Class_1  0.399531  0.350137  0.359886  0.399531  0.256572  0.171936   
       Class_2  0.509975  0.477593  0.475203  0.509975  0.138057  0.113594   
pdl1-3 Class_0  0.596592  0.669181  0.766708  0.596592  0.130710  0.131559   
       Class_1  0.667152  0.710386  0.777631  0.667152  0.159545  0.128920   
       Class_2  0.827469  0.682584  0.588864  0.827469  0.117844  0.104081   

                                    
Metric         Precision    Recall  
Model  Class                        
adsq   Class_0  0.000000  0.032359  
       Class_1  0.057753  0.000000  
br3    Class_0  0.148155  0.157296  
       Class_1  0.096139  0.256572  
       Class_2  0.142770  0.138057  
pdl1-3 Class_0  0.135361  0.130710  
       Class_1  0.116730  0.159545  
       Class_2  0.115184  0.117844

In [11]:
base_folder = os.path.join(working_directory,"eval/val")
subfolder = [name for name in os.listdir(base_folder) if os.path.isdir(os.path.join(base_folder, name))]

print(subfolder)

train_metrics = {}
train_class_metrics = {}
outer_train_metrics = {}
outer_train_class_metrics = {}

for m in subfolder:
    parent_directory = os.path.join(base_folder, m)
    subsubfolder = [name for name in os.listdir(parent_directory) if os.path.isdir(os.path.join(parent_directory, name))]
    print(subsubfolder)
    train_metrics = {}
    train_class_metrics = {}
    for s in subsubfolder: 
        sub_parent_directory = os.path.join(parent_directory, s)
        print(sub_parent_directory)
        print(s)
        train_metrics[s], train_class_metrics[s], a, n = compute_metrics(sub_parent_directory, n_classes, sub_parent_directory)
    outer_train_metrics[m] = train_metrics
    outer_train_class_metrics[m] =train_class_metrics

['adsq', 'br3', 'pdl1-3']
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/adsq/inner_iteration_1
inner_iteration_1


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.7090163934426229,
 'Balanced_Accuracy': 0.7150767042568322,
 'Precision': 0.7994308801302173,
 'Recall': 0.7090163934426229,
 'F1-Score': 0.7339227413488209,
 'Confusion Matrix': [[136, 57], [14, 37]]}

Accuracy: 0.7090163934426229
Balanced_Accuracy: 0.7150767042568322
Precision: 0.7994308801302173
Recall: 0.7090163934426229
F1-Score: 0.7339227413488209
Confusion Matrix: [[136, 57], [14, 37]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/adsq/inner_iteration_2
inner_iteration_2


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.6465863453815262,
 'Balanced_Accuracy': 0.7176616915422886,
 'Precision': 0.821425235827029,
 'Recall': 0.6465863453815262,
 'F1-Score': 0.6837636259323006,
 'Confusion Matrix': [[121, 80], [8, 40]]}

Accuracy: 0.6465863453815262
Balanced_Accuracy: 0.7176616915422886
Precision: 0.821425235827029
Recall: 0.6465863453815262
F1-Score: 0.6837636259323006
Confusion Matrix: [[121, 80], [8, 40]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/adsq/inner_iteration_3
inner_iteration_3


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.6904761904761905,
 'Balanced_Accuracy': 0.7328065554580041,
 'Precision': 0.8179664372324923,
 'Recall': 0.6904761904761905,
 'F1-Score': 0.720483803986711,
 'Confusion Matrix': [[133, 68], [10, 41]]}

Accuracy: 0.6904761904761905
Balanced_Accuracy: 0.7328065554580041
Precision: 0.8179664372324923
Recall: 0.6904761904761905
F1-Score: 0.720483803986711
Confusion Matrix: [[133, 68], [10, 41]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/adsq/inner_iteration_4
inner_iteration_4


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.6956521739130435,
 'Balanced_Accuracy': 0.7500492610837438,
 'Precision': 0.8319458466427236,
 'Recall': 0.6956521739130435,
 'F1-Score': 0.7264020163831129,
 'Confusion Matrix': [[134, 69], [8, 42]]}

Accuracy: 0.6956521739130435
Balanced_Accuracy: 0.7500492610837438
Precision: 0.8319458466427236
Recall: 0.6956521739130435
F1-Score: 0.7264020163831129
Confusion Matrix: [[134, 69], [8, 42]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/adsq/inner_iteration_5
inner_iteration_5


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.7007874015748031,
 'Balanced_Accuracy': 0.719059405940594,
 'Precision': 0.8055355793374126,
 'Recall': 0.7007874015748031,
 'F1-Score': 0.7282300421230088,
 'Confusion Matrix': [[139, 63], [13, 39]]}

Accuracy: 0.7007874015748031
Balanced_Accuracy: 0.719059405940594
Precision: 0.8055355793374126
Recall: 0.7007874015748031
F1-Score: 0.7282300421230088
Confusion Matrix: [[139, 63], [13, 39]]
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/br3/inner_iteration_1
inner_iteration_1


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3117408906882591,
 'Balanced_Accuracy': 0.31453078930592077,
 'Precision': 0.32508189673936705,
 'Recall': 0.3117408906882591,
 'F1-Score': 0.3121310094609946,
 'Confusion Matrix': [[23, 40, 31], [14, 21, 29], [27, 29, 33]]}

Accuracy: 0.3117408906882591
Balanced_Accuracy: 0.31453078930592077
Precision: 0.32508189673936705
Recall: 0.3117408906882591
F1-Score: 0.3121310094609946
Confusion Matrix: [[23, 40, 31], [14, 21, 29], [27, 29, 33]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/br3/inner_iteration_2
inner_iteration_2


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.2788844621513944,
 'Balanced_Accuracy': 0.2612835249042145,
 'Precision': 0.27749359760263514,
 'Recall': 0.2788844621513944,
 'F1-Score': 0.2755619808143658,
 'Confusion Matrix': [[36, 15, 49], [20, 8, 36], [39, 22, 26]]}

Accuracy: 0.2788844621513944
Balanced_Accuracy: 0.2612835249042145
Precision: 0.27749359760263514
Recall: 0.2788844621513944
F1-Score: 0.2755619808143658
Confusion Matrix: [[36, 15, 49], [20, 8, 36], [39, 22, 26]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/br3/inner_iteration_3
inner_iteration_3


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.316,
 'Balanced_Accuracy': 0.3141674999637697,
 'Precision': 0.32071428571428573,
 'Recall': 0.316,
 'F1-Score': 0.3176660968660968,
 'Confusion Matrix': [[31, 37, 34], [32, 18, 16], [30, 22, 30]]}

Accuracy: 0.316
Balanced_Accuracy: 0.3141674999637697
Precision: 0.32071428571428573
Recall: 0.316
F1-Score: 0.3176660968660968
Confusion Matrix: [[31, 37, 34], [32, 18, 16], [30, 22, 30]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/br3/inner_iteration_4
inner_iteration_4


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3401639344262295,
 'Balanced_Accuracy': 0.3359712461089182,
 'Precision': 0.3340759306861914,
 'Recall': 0.3401639344262295,
 'F1-Score': 0.3276402413438861,
 'Confusion Matrix': [[46, 26, 22], [31, 23, 11], [35, 36, 14]]}

Accuracy: 0.3401639344262295
Balanced_Accuracy: 0.3359712461089182
Precision: 0.3340759306861914
Recall: 0.3401639344262295
F1-Score: 0.3276402413438861
Confusion Matrix: [[46, 26, 22], [31, 23, 11], [35, 36, 14]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/br3/inner_iteration_5
inner_iteration_5


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.3373015873015873,
 'Balanced_Accuracy': 0.3415665661251536,
 'Precision': 0.3540146687750666,
 'Recall': 0.3373015873015873,
 'F1-Score': 0.3404965450393187,
 'Confusion Matrix': [[29, 42, 27], [23, 24, 18], [27, 30, 32]]}

Accuracy: 0.3373015873015873
Balanced_Accuracy: 0.3415665661251536
Precision: 0.3540146687750666
Recall: 0.3373015873015873
F1-Score: 0.3404965450393187
Confusion Matrix: [[29, 42, 27], [23, 24, 18], [27, 30, 32]]
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/pdl1-3/inner_iteration_1
inner_iteration_1


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.3853211009174312,
 'Balanced_Accuracy': 0.38597896986054875,
 'Precision': 0.3893852341909904,
 'Recall': 0.3853211009174312,
 'F1-Score': 0.3856556745108666,
 'Confusion Matrix': [[34, 18, 26], [26, 24, 26], [13, 25, 26]]}

Accuracy: 0.3853211009174312
Balanced_Accuracy: 0.38597896986054875
Precision: 0.3893852341909904
Recall: 0.3853211009174312
F1-Score: 0.3856556745108666
Confusion Matrix: [[34, 18, 26], [26, 24, 26], [13, 25, 26]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/pdl1-3/inner_iteration_2
inner_iteration_2


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.4424778761061947,
 'Balanced_Accuracy': 0.44866913541612335,
 'Precision': 0.44528937032201216,
 'Recall': 0.4424778761061947,
 'F1-Score': 0.4387443190691693,
 'Confusion Matrix': [[28, 29, 26], [18, 38, 21], [15, 17, 34]]}

Accuracy: 0.4424778761061947
Balanced_Accuracy: 0.44866913541612335
Precision: 0.44528937032201216
Recall: 0.4424778761061947
F1-Score: 0.4387443190691693
Confusion Matrix: [[28, 29, 26], [18, 38, 21], [15, 17, 34]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/pdl1-3/inner_iteration_3
inner_iteration_3


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.33183856502242154,
 'Balanced_Accuracy': 0.33505168551456105,
 'Precision': 0.34111482881443694,
 'Recall': 0.33183856502242154,
 'F1-Score': 0.3317236808535874,
 'Confusion Matrix': [[22, 18, 37], [26, 25, 28], [21, 19, 27]]}

Accuracy: 0.33183856502242154
Balanced_Accuracy: 0.33505168551456105
Precision: 0.34111482881443694
Recall: 0.33183856502242154
F1-Score: 0.3317236808535874
Confusion Matrix: [[22, 18, 37], [26, 25, 28], [21, 19, 27]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/pdl1-3/inner_iteration_4
inner_iteration_4


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.40707964601769914,
 'Balanced_Accuracy': 0.41154637543526434,
 'Precision': 0.4120911410626743,
 'Recall': 0.40707964601769914,
 'F1-Score': 0.4081663590617261,
 'Confusion Matrix': [[30, 29, 21], [35, 31, 15], [25, 9, 31]]}

Accuracy: 0.40707964601769914
Balanced_Accuracy: 0.41154637543526434
Precision: 0.4120911410626743
Recall: 0.40707964601769914
F1-Score: 0.4081663590617261
Confusion Matrix: [[30, 29, 21], [35, 31, 15], [25, 9, 31]]
/media/mmd/Samsung_T5/GitHub/UMD/eval/val/pdl1-3/inner_iteration_5
inner_iteration_5


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.3881278538812785,
 'Balanced_Accuracy': 0.3992297571309413,
 'Precision': 0.4073578874984767,
 'Recall': 0.3881278538812785,
 'F1-Score': 0.38442497213693266,
 'Confusion Matrix': [[23, 22, 33], [16, 28, 35], [20, 8, 34]]}

Accuracy: 0.3881278538812785
Balanced_Accuracy: 0.3992297571309413
Precision: 0.4073578874984767
Recall: 0.3881278538812785
F1-Score: 0.38442497213693266
Confusion Matrix: [[23, 22, 33], [16, 28, 35], [20, 8, 34]]


In [12]:
import numpy as np
import pandas as pd
from scipy.stats import sem

#train_metrics
for key, value in outer_train_metrics.items():
    print(f"Chiave: {key}, Valore: {value}")
    train_metrics = value
    # Extract metrics
    metrics = list(train_metrics['inner_iteration_1'].keys())
    metrics = metrics[:-2]
    print(metrics)

    # Compute mean and confidence interval for each metric
    summary = {}
    n = len(train_metrics)  # Number of iterations

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        print(values)
        mean_value = np.mean(values)
        confidence_interval = 2 * np.std(values, ddof=1) / np.sqrt(n)  # 2 * standard error of the mean
        
        summary[metric] = {'Mean': mean_value, 'Confidence Interval': confidence_interval}

    # Convert results to a DataFrame for visualization
    summary_df = pd.DataFrame(summary).T

    display(summary_df)

    metrics = ['Confusion Matrix']

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        #print(values)


    # Compute the mean confusion matrix
    mean_confusion_matrix = np.mean(values, axis=0)
    print(mean_confusion_matrix)

    # Compute the confidence interval (2 * standard error of the mean)
    n_matrices = values.shape[0]
    confidence_interval_matrix = 2 * np.std(values, axis=0, ddof=1) / np.sqrt(n_matrices)

    # Convert to DataFrame for better visualization
    size = mean_confusion_matrix.shape[0]
    
    mean_confusion_df = pd.DataFrame(mean_confusion_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    confidence_interval_df = pd.DataFrame(confidence_interval_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    

    display(mean_confusion_df)
    display(confidence_interval_df)

Chiave: adsq, Valore: {'inner_iteration_1': {'Accuracy': 0.7090163934426229, 'Balanced_Accuracy': 0.7150767042568322, 'Precision': 0.7994308801302173, 'Recall': 0.7090163934426229, 'F1-Score': 0.7339227413488209, 'Confusion Matrix': [[136, 57], [14, 37]]}, 'inner_iteration_2': {'Accuracy': 0.6465863453815262, 'Balanced_Accuracy': 0.7176616915422886, 'Precision': 0.821425235827029, 'Recall': 0.6465863453815262, 'F1-Score': 0.6837636259323006, 'Confusion Matrix': [[121, 80], [8, 40]]}, 'inner_iteration_3': {'Accuracy': 0.6904761904761905, 'Balanced_Accuracy': 0.7328065554580041, 'Precision': 0.8179664372324923, 'Recall': 0.6904761904761905, 'F1-Score': 0.720483803986711, 'Confusion Matrix': [[133, 68], [10, 41]]}, 'inner_iteration_4': {'Accuracy': 0.6956521739130435, 'Balanced_Accuracy': 0.7500492610837438, 'Precision': 0.8319458466427236, 'Recall': 0.6956521739130435, 'F1-Score': 0.7264020163831129, 'Confusion Matrix': [[134, 69], [8, 42]]}, 'inner_iteration_5': {'Accuracy': 0.700787401

Mean  Confidence Interval
Accuracy           0.688504             0.021834
Balanced_Accuracy  0.726931             0.013095
Precision          0.815261             0.011566
Recall             0.688504             0.021834

[[132.6  67.4]
 [ 10.6  39.8]]


Pred_0  Pred_1
True_0   132.6    67.4
True_1    10.6    39.8

Pred_0    Pred_1
True_0  6.151423  7.605261
True_1  2.497999  1.720465

Chiave: br3, Valore: {'inner_iteration_1': {'Accuracy': 0.3117408906882591, 'Balanced_Accuracy': 0.31453078930592077, 'Precision': 0.32508189673936705, 'Recall': 0.3117408906882591, 'F1-Score': 0.3121310094609946, 'Confusion Matrix': [[23, 40, 31], [14, 21, 29], [27, 29, 33]]}, 'inner_iteration_2': {'Accuracy': 0.2788844621513944, 'Balanced_Accuracy': 0.2612835249042145, 'Precision': 0.27749359760263514, 'Recall': 0.2788844621513944, 'F1-Score': 0.2755619808143658, 'Confusion Matrix': [[36, 15, 49], [20, 8, 36], [39, 22, 26]]}, 'inner_iteration_3': {'Accuracy': 0.316, 'Balanced_Accuracy': 0.3141674999637697, 'Precision': 0.32071428571428573, 'Recall': 0.316, 'F1-Score': 0.3176660968660968, 'Confusion Matrix': [[31, 37, 34], [32, 18, 16], [30, 22, 30]]}, 'inner_iteration_4': {'Accuracy': 0.3401639344262295, 'Balanced_Accuracy': 0.3359712461089182, 'Precision': 0.3340759306861914, 'Recall': 0.3401639344262295, 'F1-Score': 0.3276402413438861, 'Confusion Matrix': [[46, 26, 22], [31, 23, 11

Mean  Confidence Interval
Accuracy           0.316818             0.022045
Balanced_Accuracy  0.313504             0.028358
Precision          0.322276             0.025149
Recall             0.316818             0.022045

[[33.  32.  32.6]
 [24.  18.8 22. ]
 [31.6 27.8 27. ]]


Pred_0  Pred_1  Pred_2
True_0    33.0    32.0    32.6
True_1    24.0    18.8    22.0
True_2    31.6    27.8    27.0

Pred_0     Pred_1    Pred_2
True_0  7.720104  10.139033  9.134550
True_1  6.782330   5.775812  9.143304
True_2  4.715930   5.306600  6.928203

Chiave: pdl1-3, Valore: {'inner_iteration_1': {'Accuracy': 0.3853211009174312, 'Balanced_Accuracy': 0.38597896986054875, 'Precision': 0.3893852341909904, 'Recall': 0.3853211009174312, 'F1-Score': 0.3856556745108666, 'Confusion Matrix': [[34, 18, 26], [26, 24, 26], [13, 25, 26]]}, 'inner_iteration_2': {'Accuracy': 0.4424778761061947, 'Balanced_Accuracy': 0.44866913541612335, 'Precision': 0.44528937032201216, 'Recall': 0.4424778761061947, 'F1-Score': 0.4387443190691693, 'Confusion Matrix': [[28, 29, 26], [18, 38, 21], [15, 17, 34]]}, 'inner_iteration_3': {'Accuracy': 0.33183856502242154, 'Balanced_Accuracy': 0.33505168551456105, 'Precision': 0.34111482881443694, 'Recall': 0.33183856502242154, 'F1-Score': 0.3317236808535874, 'Confusion Matrix': [[22, 18, 37], [26, 25, 28], [21, 19, 27]]}, 'inner_iteration_4': {'Accuracy': 0.40707964601769914, 'Balanced_Accuracy': 0.41154637543526434, 'Precision': 0.4120911410626743, 'Recall': 0.40707964601769914, 'F1-Score': 0.4081663590617261, 'Confusion

Mean  Confidence Interval
Accuracy           0.390969             0.035914
Balanced_Accuracy  0.396095             0.036990
Precision          0.399048             0.034138
Recall             0.390969             0.035914

[[27.4 23.2 28.6]
 [24.2 29.2 25. ]
 [18.8 15.6 30.4]]


Pred_0  Pred_1  Pred_2
True_0    27.4    23.2    28.6
True_1    24.2    29.2    25.0
True_2    18.8    15.6    30.4

Pred_0    Pred_1    Pred_2
True_0  4.454211  4.955805  5.678028
True_1  6.764614  5.035871  6.723095
True_2  4.308132  6.374951  3.382307

In [13]:
from pyexpat import model
import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# Collect and summarize
# ------------------------------------------------------------------------------
results_list = []  # We'll accumulate dictionaries to later convert to a DataFrame

# outer_train_class_metrics might have multiple top-level keys (e.g., 'br3', 'br4', etc.)
for model_key, inner_dict in outer_train_class_metrics.items():
    # inner_dict looks like:
    # {
    #   'inner_iteration_5': {'Class_0': {...}, 'Class_1': {...}, ...},
    #   'inner_iteration_4': {...},
    #   'inner_iteration_3': {...}
    # }
    print(model_key)
    # 1) Identify all available "inner_iteration" keys
    iteration_keys = list(inner_dict.keys())
    print(iteration_keys)

    # 2) From the first iteration, identify the classes
    #    (Assumes same classes appear in each iteration, or you can unify them if needed)
    first_iteration = iteration_keys[0]
    class_names = list(inner_dict[first_iteration].keys())
    print(class_names)
    
    # 3) For each class, gather metric lists across iterations
    for class_name in class_names:
        # We'll track each metric: Accuracy, Precision, Recall, F1-score
        # You could also extract these keys on the fly if each class dict has more/less.
        metric_names = ["Accuracy", "Precision", "Recall", "F1-score"]
        
        # For storing raw values across all iterations
        metrics_storage = {metric: [] for metric in metric_names}
        
        # 4) Loop over each iteration to collect values
        for iteration_key in iteration_keys:
            iteration_data = inner_dict[iteration_key]
            if class_name in iteration_data:
                class_metrics = iteration_data[class_name]
                # class_metrics is e.g. {'Accuracy': 0.81, 'Precision': 0.82, ...}
                for metric in metric_names:
                    if metric in class_metrics:
                        metrics_storage[metric].append(class_metrics[metric])
        
        # 5) Compute mean & CI for each metric in metrics_storage
        for metric, values in metrics_storage.items():
            if len(values) == 0:
                continue  # skip if no data was found for some reason
            
            mean_val, ci_val = compute_mean_and_ci(values)

            results_list.append({
                "Model":  model_key,
                "Class":  class_name,
                "Metric": metric,
                "Mean":   mean_val,
                "95% CI": ci_val
            })

# ------------------------------------------------------------------------------
# Convert the collected results into a DataFrame
# ------------------------------------------------------------------------------
summary_df = pd.DataFrame(results_list)

# If desired, you can pivot or group:
# e.g., pivot to see each (Class, Metric) as a row with columns = ["Mean", "95% CI"]
# We'll keep it in "long" format here:
display(summary_df)

#Optionally, you could pivot for a more "matrix-like" view:
pivot_df_val = summary_df.pivot(index=["Model","Class"], 
                             columns="Metric", 
                            values=["Mean","95% CI"])
display(pivot_df_val)

adsq
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1']
br3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']
pdl1-3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']


Model    Class     Metric      Mean    95% CI
0     adsq  Class_0   Accuracy  0.663312  0.034925
1     adsq  Class_0  Precision  0.926571  0.013980
2     adsq  Class_0     Recall  0.663312  0.034925
3     adsq  Class_0   F1-score  0.772343  0.020676
4     adsq  Class_1   Accuracy  0.790549  0.045457
5     adsq  Class_1  Precision  0.372766  0.020613
6     adsq  Class_1     Recall  0.790549  0.045457
7     adsq  Class_1   F1-score  0.505454  0.015467
8      br3  Class_0   Accuracy  0.338776  0.083704
9      br3  Class_0  Precision  0.369892  0.025312
10     br3  Class_0     Recall  0.338776  0.083704
11     br3  Class_0   F1-score  0.350521  0.054204
12     br3  Class_1   Accuracy  0.289786  0.088691
13     br3  Class_1  Precision  0.233093  0.030829
14     br3  Class_1     Recall  0.289786  0.088691
15     br3  Class_1   F1-score  0.255214  0.057558
16     br3  Class_2   Accuracy  0.311949  0.078084
17     br3  Class_2  Precision  0.335506  0.063275
18     br3  Class_2     Recall  0.311949  0.078084
19     br3  Class_2   F1-score  0.318659  0.068661
20  pdl1-3  Class_0   Accuracy  0.345767  0.055219
21  pdl1-3  Class_0  Precision  0.393355  0.061189
22  pdl1-3  Class_0     Recall  0.345767  0.055219
23  pdl1-3  Class_0   F1-score  0.365859  0.050788
24  pdl1-3  Class_1   Accuracy  0.372580  0.065468
25  pdl1-3  Class_1  Precision  0.429170  0.043642
26  pdl1-3  Class_1     Recall  0.372580  0.065468
27  pdl1-3  Class_1   F1-score  0.396883  0.048159
28  pdl1-3  Class_2   Accuracy  0.469939  0.057942
29  pdl1-3  Class_2  Precision  0.368517  0.062609
30  pdl1-3  Class_2     Recall  0.469939  0.057942
31  pdl1-3  Class_2   F1-score  0.410547  0.051421

Mean                                  95% CI            \
Metric          Accuracy  F1-score Precision    Recall  Accuracy  F1-score   
Model  Class                                                                 
adsq   Class_0  0.663312  0.772343  0.926571  0.663312  0.034925  0.020676   
       Class_1  0.790549  0.505454  0.372766  0.790549  0.045457  0.015467   
br3    Class_0  0.338776  0.350521  0.369892  0.338776  0.083704  0.054204   
       Class_1  0.289786  0.255214  0.233093  0.289786  0.088691  0.057558   
       Class_2  0.311949  0.318659  0.335506  0.311949  0.078084  0.068661   
pdl1-3 Class_0  0.345767  0.365859  0.393355  0.345767  0.055219  0.050788   
       Class_1  0.372580  0.396883  0.429170  0.372580  0.065468  0.048159   
       Class_2  0.469939  0.410547  0.368517  0.469939  0.057942  0.051421   

                                    
Metric         Precision    Recall  
Model  Class                        
adsq   Class_0  0.013980  0.034925  
       Class_1  0.020613  0.045457  
br3    Class_0  0.025312  0.083704  
       Class_1  0.030829  0.088691  
       Class_2  0.063275  0.078084  
pdl1-3 Class_0  0.061189  0.055219  
       Class_1  0.043642  0.065468  
       Class_2  0.062609  0.057942

In [14]:
base_folder = os.path.join(working_directory,"eval/test-int")
subfolder = [name for name in os.listdir(base_folder) if os.path.isdir(os.path.join(base_folder, name))]

print(subfolder)

train_metrics = {}
train_class_metrics = {}
outer_train_metrics = {}
outer_train_class_metrics = {}

for m in subfolder:
    parent_directory = os.path.join(base_folder, m)
    subsubfolder = [name for name in os.listdir(parent_directory) if os.path.isdir(os.path.join(parent_directory, name))]
    print(subsubfolder)
    train_metrics = {}
    train_class_metrics = {}
    for s in subsubfolder: 
        sub_parent_directory = os.path.join(parent_directory, s)
        print(sub_parent_directory)
        print(s)
        train_metrics[s], train_class_metrics[s], a, n = compute_metrics(sub_parent_directory, n_classes, sub_parent_directory)
        print(n)
    outer_train_metrics[m] = train_metrics
    outer_train_class_metrics[m] =train_class_metrics

['adsq', 'br3', 'pdl1-3']
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/adsq/inner_iteration_1
inner_iteration_1


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.6231884057971014,
 'Balanced_Accuracy': 0.7061403508771931,
 'Precision': 0.8300328827183047,
 'Recall': 0.6231884057971014,
 'F1-Score': 0.668241965973535,
 'Confusion Matrix': [[33, 24], [2, 10]]}

Accuracy: 0.6231884057971014
Balanced_Accuracy: 0.7061403508771931
Precision: 0.8300328827183047
Recall: 0.6231884057971014
F1-Score: 0.668241965973535
Confusion Matrix: [[33, 24], [2, 10]]
['Class adenocarcinoma', 'Class squamous']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/adsq/inner_iteration_2
inner_iteration_2


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.75,
 'Balanced_Accuracy': 0.7673469387755103,
 'Precision': 0.8192307692307692,
 'Recall': 0.75,
 'F1-Score': 0.7670454545454546,
 'Confusion Matrix': [[36, 13], [3, 12]]}

Accuracy: 0.75
Balanced_Accuracy: 0.7673469387755103
Precision: 0.8192307692307692
Recall: 0.75
F1-Score: 0.7670454545454546
Confusion Matrix: [[36, 13], [3, 12]]
['Class adenocarcinoma', 'Class squamous']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/adsq/inner_iteration_3
inner_iteration_3


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.7868852459016393,
 'Balanced_Accuracy': 0.7414965986394557,
 'Precision': 0.8228280880161305,
 'Recall': 0.7868852459016393,
 'F1-Score': 0.7995283162226395,
 'Confusion Matrix': [[40, 9], [4, 8]]}

Accuracy: 0.7868852459016393
Balanced_Accuracy: 0.7414965986394557
Precision: 0.8228280880161305
Recall: 0.7868852459016393
F1-Score: 0.7995283162226395
Confusion Matrix: [[40, 9], [4, 8]]
['Class adenocarcinoma', 'Class squamous']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/adsq/inner_iteration_4
inner_iteration_4


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.6666666666666666,
 'Balanced_Accuracy': 0.7037643207855975,
 'Precision': 0.7923681257014591,
 'Recall': 0.6666666666666666,
 'F1-Score': 0.6958333333333333,
 'Confusion Matrix': [[30, 17], [3, 10]]}

Accuracy: 0.6666666666666666
Balanced_Accuracy: 0.7037643207855975
Precision: 0.7923681257014591
Recall: 0.6666666666666666
F1-Score: 0.6958333333333333
Confusion Matrix: [[30, 17], [3, 10]]
['Class adenocarcinoma', 'Class squamous']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/adsq/inner_iteration_5
inner_iteration_5


{'0': 'adenocarcinoma', '1': 'squamous'}

This is outlab 2
HISTOLOGY


{'Accuracy': 0.7288135593220338,
 'Balanced_Accuracy': 0.728219696969697,
 'Precision': 0.8203559746824689,
 'Recall': 0.7288135593220338,
 'F1-Score': 0.7554197871501773,
 'Confusion Matrix': [[35, 13], [3, 8]]}

Accuracy: 0.7288135593220338
Balanced_Accuracy: 0.728219696969697
Precision: 0.8203559746824689
Recall: 0.7288135593220338
F1-Score: 0.7554197871501773
Confusion Matrix: [[35, 13], [3, 8]]
['Class adenocarcinoma', 'Class squamous']
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/br3/inner_iteration_1
inner_iteration_1


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.34375,
 'Balanced_Accuracy': 0.36808934099955765,
 'Precision': 0.34107067062818336,
 'Recall': 0.34375,
 'F1-Score': 0.3204513888888889,
 'Confusion Matrix': [[5, 11, 12], [5, 5, 7], [4, 3, 12]]}

Accuracy: 0.34375
Balanced_Accuracy: 0.36808934099955765
Precision: 0.34107067062818336
Recall: 0.34375
F1-Score: 0.3204513888888889
Confusion Matrix: [[5, 11, 12], [5, 5, 7], [4, 3, 12]]
['Class 0.0', 'Class 1.0', 'Class 2.0']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/br3/inner_iteration_2
inner_iteration_2


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.4,
 'Balanced_Accuracy': 0.3899923605805959,
 'Precision': 0.48125,
 'Recall': 0.4,
 'F1-Score': 0.33689440993788816,
 'Confusion Matrix': [[3, 0, 19], [3, 3, 11], [2, 1, 18]]}

Accuracy: 0.4
Balanced_Accuracy: 0.3899923605805959
Precision: 0.48125
Recall: 0.4
F1-Score: 0.33689440993788816
Confusion Matrix: [[3, 0, 19], [3, 3, 11], [2, 1, 18]]
['Class 0.0', 'Class 1.0', 'Class 2.0']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/br3/inner_iteration_3
inner_iteration_3


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.32786885245901637,
 'Balanced_Accuracy': 0.3397435897435897,
 'Precision': 0.34601188764260377,
 'Recall': 0.32786885245901637,
 'F1-Score': 0.32906056650664073,
 'Confusion Matrix': [[7, 4, 9], [6, 6, 3], [5, 14, 7]]}

Accuracy: 0.32786885245901637
Balanced_Accuracy: 0.3397435897435897
Precision: 0.34601188764260377
Recall: 0.32786885245901637
F1-Score: 0.32906056650664073
Confusion Matrix: [[7, 4, 9], [6, 6, 3], [5, 14, 7]]
['Class 0.0', 'Class 1.0', 'Class 2.0']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/br3/inner_iteration_4
inner_iteration_4


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.43283582089552236,
 'Balanced_Accuracy': 0.37603519668737057,
 'Precision': 0.4028073916133618,
 'Recall': 0.43283582089552236,
 'F1-Score': 0.38156065049060023,
 'Confusion Matrix': [[22, 2, 4], [11, 2, 3], [15, 3, 5]]}

Accuracy: 0.43283582089552236
Balanced_Accuracy: 0.37603519668737057
Precision: 0.4028073916133618
Recall: 0.43283582089552236
F1-Score: 0.38156065049060023
Confusion Matrix: [[22, 2, 4], [11, 2, 3], [15, 3, 5]]
['Class 0.0', 'Class 1.0', 'Class 2.0']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/br3/inner_iteration_5
inner_iteration_5


{'0': '0.0', '1': '1.0', '2': '2.0'}

This is outlab 3
BEST_RESPONSE_3


{'Accuracy': 0.2542372881355932,
 'Balanced_Accuracy': 0.268640350877193,
 'Precision': 0.2948631029986962,
 'Recall': 0.2542372881355932,
 'F1-Score': 0.24330471788098906,
 'Confusion Matrix': [[3, 13, 8], [1, 5, 10], [4, 8, 7]]}

Accuracy: 0.2542372881355932
Balanced_Accuracy: 0.268640350877193
Precision: 0.2948631029986962
Recall: 0.2542372881355932
F1-Score: 0.24330471788098906
Confusion Matrix: [[3, 13, 8], [1, 5, 10], [4, 8, 7]]
['Class 0.0', 'Class 1.0', 'Class 2.0']
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/pdl1-3/inner_iteration_1
inner_iteration_1


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.3,
 'Balanced_Accuracy': 0.31342840166369573,
 'Precision': 0.2881944444444444,
 'Recall': 0.3,
 'F1-Score': 0.28416387693288697,
 'Confusion Matrix': [[7, 7, 7], [10, 3, 9], [7, 2, 8]]}

Accuracy: 0.3
Balanced_Accuracy: 0.31342840166369573
Precision: 0.2881944444444444
Recall: 0.3
F1-Score: 0.28416387693288697
Confusion Matrix: [[7, 7, 7], [10, 3, 9], [7, 2, 8]]
['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/pdl1-3/inner_iteration_2
inner_iteration_2


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.40384615384615385,
 'Balanced_Accuracy': 0.4081349206349206,
 'Precision': 0.3661581839213418,
 'Recall': 0.40384615384615385,
 'F1-Score': 0.35861977170116704,
 'Confusion Matrix': [[1, 7, 8], [3, 9, 9], [1, 3, 11]]}

Accuracy: 0.40384615384615385
Balanced_Accuracy: 0.4081349206349206
Precision: 0.3661581839213418
Recall: 0.40384615384615385
F1-Score: 0.35861977170116704
Confusion Matrix: [[1, 7, 8], [3, 9, 9], [1, 3, 11]]
['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/pdl1-3/inner_iteration_3
inner_iteration_3


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.2909090909090909,
 'Balanced_Accuracy': 0.3212576896787423,
 'Precision': 0.27636363636363637,
 'Recall': 0.2909090909090909,
 'F1-Score': 0.2755773955773956,
 'Confusion Matrix': [[4, 11, 7], [9, 4, 6], [2, 4, 8]]}

Accuracy: 0.2909090909090909
Balanced_Accuracy: 0.3212576896787423
Precision: 0.27636363636363637
Recall: 0.2909090909090909
F1-Score: 0.2755773955773956
Confusion Matrix: [[4, 11, 7], [9, 4, 6], [2, 4, 8]]
['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/pdl1-3/inner_iteration_4
inner_iteration_4


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.38461538461538464,
 'Balanced_Accuracy': 0.38544891640866874,
 'Precision': 0.3844255292219093,
 'Recall': 0.38461538461538464,
 'F1-Score': 0.3791273054430949,
 'Confusion Matrix': [[8, 5, 6], [5, 4, 8], [4, 4, 8]]}

Accuracy: 0.38461538461538464
Balanced_Accuracy: 0.38544891640866874
Precision: 0.3844255292219093
Recall: 0.38461538461538464
F1-Score: 0.3791273054430949
Confusion Matrix: [[8, 5, 6], [5, 4, 8], [4, 4, 8]]
['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']
/media/mmd/Samsung_T5/GitHub/UMD/eval/test-int/pdl1-3/inner_iteration_5
inner_iteration_5


{'0': '1-49 %', '1': '< 1 %', '2': '>=50 %'}

This is outlab 3
PDL1_CATHEGORY


{'Accuracy': 0.4745762711864407,
 'Balanced_Accuracy': 0.48120300751879697,
 'Precision': 0.49012922917072543,
 'Recall': 0.4745762711864407,
 'F1-Score': 0.46451921875650687,
 'Confusion Matrix': [[6, 4, 11], [3, 10, 6], [3, 4, 12]]}

Accuracy: 0.4745762711864407
Balanced_Accuracy: 0.48120300751879697
Precision: 0.49012922917072543
Recall: 0.4745762711864407
F1-Score: 0.46451921875650687
Confusion Matrix: [[6, 4, 11], [3, 10, 6], [3, 4, 12]]
['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']


In [15]:
print(n)

['Class 1-49 %', 'Class < 1 %', 'Class >=50 %']


In [16]:
import numpy as np
import pandas as pd
from scipy.stats import sem

#train_metrics
for key, value in outer_train_metrics.items():
    print(f"Chiave: {key}, Valore: {value}")
    train_metrics = value
    # Extract metrics
    metrics = list(train_metrics['inner_iteration_1'].keys())
    #metrics = metrics[:-2]
    print(metrics)

    # Compute mean and confidence interval for each metric
    summary = {}
    n = len(train_metrics)  # Number of iterations

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        print(values)
        mean_value = np.mean(values)
        confidence_interval = 2 * np.std(values, ddof=1) / np.sqrt(n)  # 2 * standard error of the mean
        
        summary[metric] = {'Mean': mean_value, 'Confidence Interval': confidence_interval}

    # Convert results to a DataFrame for visualization
    summary_df = pd.DataFrame(summary).T

    display(summary_df)

    metrics = ['Confusion Matrix']

    for metric in metrics:
        values = np.array([train_metrics[key][metric] for key in train_metrics.keys()])
        #print(values)


    # Compute the mean confusion matrix
    mean_confusion_matrix = np.mean(values, axis=0)
    print(mean_confusion_matrix)

    # Compute the confidence interval (2 * standard error of the mean)
    n_matrices = values.shape[0]
    confidence_interval_matrix = 2 * np.std(values, axis=0, ddof=1) / np.sqrt(n_matrices)

    # Convert to DataFrame for better visualization
    size = mean_confusion_matrix.shape[0]
    
    mean_confusion_df = pd.DataFrame(mean_confusion_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    confidence_interval_df = pd.DataFrame(confidence_interval_matrix, columns=[f'Pred_{i}' for i in range(size)], index=[f'True_{i}' for i in range(size)])
    

    display(mean_confusion_df)
    display(confidence_interval_df)

Chiave: adsq, Valore: {'inner_iteration_1': {'Accuracy': 0.6231884057971014, 'Balanced_Accuracy': 0.7061403508771931, 'Precision': 0.8300328827183047, 'Recall': 0.6231884057971014, 'F1-Score': 0.668241965973535, 'Confusion Matrix': [[33, 24], [2, 10]]}, 'inner_iteration_2': {'Accuracy': 0.75, 'Balanced_Accuracy': 0.7673469387755103, 'Precision': 0.8192307692307692, 'Recall': 0.75, 'F1-Score': 0.7670454545454546, 'Confusion Matrix': [[36, 13], [3, 12]]}, 'inner_iteration_3': {'Accuracy': 0.7868852459016393, 'Balanced_Accuracy': 0.7414965986394557, 'Precision': 0.8228280880161305, 'Recall': 0.7868852459016393, 'F1-Score': 0.7995283162226395, 'Confusion Matrix': [[40, 9], [4, 8]]}, 'inner_iteration_4': {'Accuracy': 0.6666666666666666, 'Balanced_Accuracy': 0.7037643207855975, 'Precision': 0.7923681257014591, 'Recall': 0.6666666666666666, 'F1-Score': 0.6958333333333333, 'Confusion Matrix': [[30, 17], [3, 10]]}, 'inner_iteration_5': {'Accuracy': 0.7288135593220338, 'Balanced_Accuracy': 0.728

Mean  Confidence Interval
Accuracy            0.711111             0.058776
Balanced_Accuracy   0.729394             0.023605
Precision           0.816963             0.012859
Recall              0.711111             0.058776
F1-Score            0.737214             0.048112
Confusion Matrix   15.650000            11.266251

[[34.8 15.2]
 [ 3.   9.6]]


Pred_0  Pred_1
True_0    34.8    15.2
True_1     3.0     9.6

Pred_0    Pred_1
True_0  3.310589  5.075431
True_1  0.632456  1.496663

Chiave: br3, Valore: {'inner_iteration_1': {'Accuracy': 0.34375, 'Balanced_Accuracy': 0.36808934099955765, 'Precision': 0.34107067062818336, 'Recall': 0.34375, 'F1-Score': 0.3204513888888889, 'Confusion Matrix': [[5, 11, 12], [5, 5, 7], [4, 3, 12]]}, 'inner_iteration_2': {'Accuracy': 0.4, 'Balanced_Accuracy': 0.3899923605805959, 'Precision': 0.48125, 'Recall': 0.4, 'F1-Score': 0.33689440993788816, 'Confusion Matrix': [[3, 0, 19], [3, 3, 11], [2, 1, 18]]}, 'inner_iteration_3': {'Accuracy': 0.32786885245901637, 'Balanced_Accuracy': 0.3397435897435897, 'Precision': 0.34601188764260377, 'Recall': 0.32786885245901637, 'F1-Score': 0.32906056650664073, 'Confusion Matrix': [[7, 4, 9], [6, 6, 3], [5, 14, 7]]}, 'inner_iteration_4': {'Accuracy': 0.43283582089552236, 'Balanced_Accuracy': 0.37603519668737057, 'Precision': 0.4028073916133618, 'Recall': 0.43283582089552236, 'F1-Score': 0.38156065049060023, 'Confusion Matrix': [[22, 2, 4], [11, 2, 3], [15, 3, 5]]}, 'inner_iteration_5': {'Accuracy': 0.

Mean  Confidence Interval
Accuracy           0.351738             0.061719
Balanced_Accuracy  0.348500             0.043169
Precision          0.373201             0.063968
Recall             0.351738             0.061719
F1-Score           0.322254             0.044753
Confusion Matrix   6.911111             4.548015

[[ 8.   6.  10.4]
 [ 5.2  4.2  6.8]
 [ 6.   5.8  9.8]]


Pred_0  Pred_1  Pred_2
True_0     8.0     6.0    10.4
True_1     5.2     4.2     6.8
True_2     6.0     5.8     9.8

Pred_0    Pred_1    Pred_2
True_0  7.155418  5.099020  5.003998
True_1  3.370460  1.469694  3.370460
True_2  4.604346  4.707441  4.707441

Chiave: pdl1-3, Valore: {'inner_iteration_1': {'Accuracy': 0.3, 'Balanced_Accuracy': 0.31342840166369573, 'Precision': 0.2881944444444444, 'Recall': 0.3, 'F1-Score': 0.28416387693288697, 'Confusion Matrix': [[7, 7, 7], [10, 3, 9], [7, 2, 8]]}, 'inner_iteration_2': {'Accuracy': 0.40384615384615385, 'Balanced_Accuracy': 0.4081349206349206, 'Precision': 0.3661581839213418, 'Recall': 0.40384615384615385, 'F1-Score': 0.35861977170116704, 'Confusion Matrix': [[1, 7, 8], [3, 9, 9], [1, 3, 11]]}, 'inner_iteration_3': {'Accuracy': 0.2909090909090909, 'Balanced_Accuracy': 0.3212576896787423, 'Precision': 0.27636363636363637, 'Recall': 0.2909090909090909, 'F1-Score': 0.2755773955773956, 'Confusion Matrix': [[4, 11, 7], [9, 4, 6], [2, 4, 8]]}, 'inner_iteration_4': {'Accuracy': 0.38461538461538464, 'Balanced_Accuracy': 0.38544891640866874, 'Precision': 0.3844255292219093, 'Recall': 0.38461538461538464, 'F1-Score': 0.3791273054430949, 'Confusion Matrix': [[8, 5, 6], [5, 4, 8], [4, 4, 8]]}, 'inner_it

Mean  Confidence Interval
Accuracy           0.370789             0.068480
Balanced_Accuracy  0.381895             0.061527
Precision          0.361054             0.077089
Recall             0.370789             0.068480
F1-Score           0.352402             0.069111
Confusion Matrix   6.177778             2.588709

[[5.2 6.8 7.8]
 [6.  6.  7.6]
 [3.4 3.4 9.4]]


Pred_0  Pred_1  Pred_2
True_0     5.2     6.8     7.8
True_1     6.0     6.0     7.6
True_2     3.4     3.4     9.4

Pred_0    Pred_1    Pred_2
True_0  2.481935  2.400000  1.720465
True_1  2.966479  2.898275  1.356466
True_2  2.059126  0.800000  1.743560

In [17]:
from pyexpat import model
import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# Collect and summarize
# ------------------------------------------------------------------------------
results_list = []  # We'll accumulate dictionaries to later convert to a DataFrame

# outer_train_class_metrics might have multiple top-level keys (e.g., 'br3', 'br4', etc.)
for model_key, inner_dict in outer_train_class_metrics.items():
    # inner_dict looks like:
    # {
    #   'inner_iteration_5': {'Class_0': {...}, 'Class_1': {...}, ...},
    #   'inner_iteration_4': {...},
    #   'inner_iteration_3': {...}
    # }
    print(model_key)
    # 1) Identify all available "inner_iteration" keys
    iteration_keys = list(inner_dict.keys())
    print(iteration_keys)

    # 2) From the first iteration, identify the classes
    #    (Assumes same classes appear in each iteration, or you can unify them if needed)
    first_iteration = iteration_keys[0]
    class_names = list(inner_dict[first_iteration].keys())
    print(class_names)
    
    # 3) For each class, gather metric lists across iterations
    for class_name in class_names:
        # We'll track each metric: Accuracy, Precision, Recall, F1-score
        # You could also extract these keys on the fly if each class dict has more/less.
        metric_names = ["Accuracy", "Precision", "Recall", "F1-score"]
        
        # For storing raw values across all iterations
        metrics_storage = {metric: [] for metric in metric_names}
        
        # 4) Loop over each iteration to collect values
        for iteration_key in iteration_keys:
            iteration_data = inner_dict[iteration_key]
            if class_name in iteration_data:
                class_metrics = iteration_data[class_name]
                # class_metrics is e.g. {'Accuracy': 0.81, 'Precision': 0.82, ...}
                for metric in metric_names:
                    if metric in class_metrics:
                        metrics_storage[metric].append(class_metrics[metric])
        
        # 5) Compute mean & CI for each metric in metrics_storage
        for metric, values in metrics_storage.items():
            if len(values) == 0:
                continue  # skip if no data was found for some reason
            
            mean_val, ci_val = compute_mean_and_ci(values)

            results_list.append({
                "Model":  model_key,
                "Class":  class_name,
                "Metric": metric,
                "Mean":   mean_val,
                "95% CI": ci_val
            })

# ------------------------------------------------------------------------------
# Convert the collected results into a DataFrame
# ------------------------------------------------------------------------------
summary_df = pd.DataFrame(results_list)

# If desired, you can pivot or group:
# e.g., pivot to see each (Class, Metric) as a row with columns = ["Mean", "95% CI"]
# We'll keep it in "long" format here:
display(summary_df)

#Optionally, you could pivot for a more "matrix-like" view:
pivot_df_test = summary_df.pivot(index=["Model","Class"], 
                             columns="Metric", 
                            values=["Mean","95% CI"])
display(pivot_df_test)

adsq
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1']
br3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']
pdl1-3
['inner_iteration_1', 'inner_iteration_2', 'inner_iteration_3', 'inner_iteration_4', 'inner_iteration_5']
['Class_0', 'Class_1', 'Class_2']


Model    Class     Metric      Mean    95% CI
0     adsq  Class_0   Accuracy  0.699486  0.082518
1     adsq  Class_0  Precision  0.921034  0.012375
2     adsq  Class_0     Recall  0.699486  0.082518
3     adsq  Class_0   F1-score  0.791948  0.051286
4     adsq  Class_1   Accuracy  0.759301  0.058039
5     adsq  Class_1  Precision  0.399206  0.069038
6     adsq  Class_1     Recall  0.759301  0.058039
7     adsq  Class_1   F1-score  0.517301  0.055555
8      br3  Class_0   Accuracy  0.315130  0.248765
9      br3  Class_0  Precision  0.390873  0.035204
10     br3  Class_0     Recall  0.315130  0.248765
11     br3  Class_0   F1-score  0.314593  0.146913
12     br3  Class_1   Accuracy  0.261618  0.098701
13     br3  Class_1  Precision  0.348236  0.203237
14     br3  Class_1     Recall  0.261618  0.098701
15     br3  Class_1   F1-score  0.256639  0.047087
16     br3  Class_2   Accuracy  0.468753  0.241005
17     br3  Class_2  Precision  0.365437  0.045811
18     br3  Class_2     Recall  0.468753  0.241005
19     br3  Class_2   F1-score  0.383349  0.097459
20  pdl1-3  Class_0   Accuracy  0.256884  0.124135
21  pdl1-3  Class_0  Precision  0.345784  0.118152
22  pdl1-3  Class_0     Recall  0.256884  0.124135
23  pdl1-3  Class_0   F1-score  0.286129  0.120849
24  pdl1-3  Class_1   Accuracy  0.307414  0.145907
25  pdl1-3  Class_1  Precision  0.359492  0.132923
26  pdl1-3  Class_1     Recall  0.307414  0.145907
27  pdl1-3  Class_1   F1-score  0.328841  0.141829
28  pdl1-3  Class_2   Accuracy  0.581386  0.094452
29  pdl1-3  Class_2  Precision  0.376914  0.027225
30  pdl1-3  Class_2     Recall  0.581386  0.094452
31  pdl1-3  Class_2   F1-score  0.456013  0.045993

Mean                                  95% CI            \
Metric          Accuracy  F1-score Precision    Recall  Accuracy  F1-score   
Model  Class                                                                 
adsq   Class_0  0.699486  0.791948  0.921034  0.699486  0.082518  0.051286   
       Class_1  0.759301  0.517301  0.399206  0.759301  0.058039  0.055555   
br3    Class_0  0.315130  0.314593  0.390873  0.315130  0.248765  0.146913   
       Class_1  0.261618  0.256639  0.348236  0.261618  0.098701  0.047087   
       Class_2  0.468753  0.383349  0.365437  0.468753  0.241005  0.097459   
pdl1-3 Class_0  0.256884  0.286129  0.345784  0.256884  0.124135  0.120849   
       Class_1  0.307414  0.328841  0.359492  0.307414  0.145907  0.141829   
       Class_2  0.581386  0.456013  0.376914  0.581386  0.094452  0.045993   

                                    
Metric         Precision    Recall  
Model  Class                        
adsq   Class_0  0.012375  0.082518  
       Class_1  0.069038  0.058039  
br3    Class_0  0.035204  0.248765  
       Class_1  0.203237  0.098701  
       Class_2  0.045811  0.241005  
pdl1-3 Class_0  0.118152  0.124135  
       Class_1  0.132923  0.145907  
       Class_2  0.027225  0.094452

In [18]:
new_class_names = ["adeno", "squamous", "BR0", "BR1", "BR2", '1-49 %',  '< 1 %', '>=50 %']


In [19]:


# Creare una mappatura dall'ordine originale ai nuovi nomi
pivot_df_test.index = pd.MultiIndex.from_tuples(
    [(model, new_class_names[i]) for i, (model, cls) in enumerate(pivot_df_test.index)],
    names=['Model', 'Class']
)




In [20]:
pivot_df_test



Mean                                  95% CI            \
Metric           Accuracy  F1-score Precision    Recall  Accuracy  F1-score   
Model  Class                                                                  
adsq   adeno     0.699486  0.791948  0.921034  0.699486  0.082518  0.051286   
       squamous  0.759301  0.517301  0.399206  0.759301  0.058039  0.055555   
br3    BR0       0.315130  0.314593  0.390873  0.315130  0.248765  0.146913   
       BR1       0.261618  0.256639  0.348236  0.261618  0.098701  0.047087   
       BR2       0.468753  0.383349  0.365437  0.468753  0.241005  0.097459   
pdl1-3 1-49 %    0.256884  0.286129  0.345784  0.256884  0.124135  0.120849   
       < 1 %     0.307414  0.328841  0.359492  0.307414  0.145907  0.141829   
       >=50 %    0.581386  0.456013  0.376914  0.581386  0.094452  0.045993   

                                     
Metric          Precision    Recall  
Model  Class                         
adsq   adeno     0.012375  0.082518  
       squamous  0.069038  0.058039  
br3    BR0       0.035204  0.248765  
       BR1       0.203237  0.098701  
       BR2       0.045811  0.241005  
pdl1-3 1-49 %    0.118152  0.124135  
       < 1 %     0.132923  0.145907  
       >=50 %    0.027225  0.094452

In [21]:
# Ottenere l'index attuale
index_values = list(pivot_df_test.index)

# Scambiare la penultima e la terzultima riga (nomi delle classi)
index_values[-3], index_values[-2] = index_values[-2], index_values[-3]

# Scambiare anche i valori delle righe corrispondenti
pivot_df_test.iloc[-3], pivot_df_test.iloc[-2] = pivot_df_test.iloc[-2].copy(), pivot_df_test.iloc[-3].copy()

# Prendere i valori attuali del livello "Class"
class_index = pivot_df_test.index.get_level_values("Class").to_list()

# Scambiare solo la penultima e la terzultima voce
class_index[-3], class_index[-2] = class_index[-2], class_index[-3]

# Applicare i nuovi nomi alla colonna "Class" senza modificare i dati
pivot_df_test.index = pd.MultiIndex.from_arrays(
    [pivot_df_test.index.get_level_values("Model"), class_index], names=["Model", "Class"]
)



In [30]:
pivot_df_test.to_csv("Accuracy_metrics_per_class.csv")

In [31]:
df = pd.read_csv("Accuracy_metrics_per_class.csv")

In [32]:
df

Unnamed: 0 Unnamed: 1                 Mean               Mean.1  \
0     Metric        NaN             Accuracy             F1-score   
1      Model      Class                  NaN                  NaN   
2       adsq      adeno    0.699486463118282   0.7919483329330357   
3       adsq   squamous   0.7593006993006993   0.5173013493253373   
4        br3        BR0  0.31512987012987015   0.3145927318295739   
5        br3        BR1   0.2616176470588235  0.25663853055157404   
6        br3        BR2   0.4687529861442904  0.38334926908839956   
7     pdl1-3      < 1 %  0.30741425756905627    0.328840822246395   
8     pdl1-3     1-49 %   0.2568836864889496   0.2861292461292462   
9     pdl1-3     >=50 %   0.5813858174848887   0.4560134596275146   

                Mean.2               Mean.3               95% CI  \
0            Precision               Recall             Accuracy   
1                  NaN                  NaN                  NaN   
2   0.9210337031389664    0.699486463118282  0.08251762827119251   
3  0.39920572673513843   0.7593006993006993  0.05803916826127972   
4  0.39087301587301587  0.31512987012987015  0.24876517439526014   
5  0.34823597455176397   0.2616176470588235   0.0987009043125276   
6   0.3654368986983588   0.4687529861442904  0.24100510058622315   
7   0.3594916779127305  0.30741425756905627   0.1459067123986441   
8  0.34578431372549023   0.2568836864889496   0.1241346382367121   
9  0.37691446484549934   0.5813858174848887   0.0944524220081717   

               95% CI.1              95% CI.2             95% CI.3  
0              F1-score             Precision               Recall  
1                   NaN                   NaN                  NaN  
2  0.051285828324105706  0.012374960900804597  0.08251762827119251  
3   0.05555539781311326   0.06903816918136436  0.05803916826127972  
4   0.14691275317512753  0.035203579549550584  0.24876517439526014  
5   0.04708739826863728    0.2032365662395314   0.0987009043125276  
6   0.09745856105370587   0.04581148561867428  0.24100510058622315  
7    0.1418287371110277   0.13292348176370944   0.1459067123986441  
8   0.12084900669842773   0.11815234628203218   0.1241346382367121  
9   0.04599337382114896  0.027225468699231294   0.0944524220081717

In [ ]:
df